# coding: utf-8

"""
    Swagger Delivery

    Отвечает за учет курьеров, деспетчеризацию доставок, доставку

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from OpenApi.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_courier(self) -> None:
        """Test case for create_courier

        Добавить курьера
        """
        pass

    def test_create_order(self) -> None:
        """Test case for create_order

        Создать заказ
        """
        pass

    def test_get_couriers(self) -> None:
        """Test case for get_couriers

        Получить всех курьеров
        """
        pass

    def test_get_orders(self) -> None:
        """Test case for get_orders

        Получить все незавершенные заказы
        """
        pass


if __name__ == '__main__':
    unittest.main()
