# coding: utf-8

# flake8: noqa
"""
    Swagger Delivery

    Отвечает за учет курьеров, деспетчеризацию доставок, доставку

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from OpenApi.models.courier import Courier
from OpenApi.models.error import Error
from OpenApi.models.location import Location
from OpenApi.models.new_courier import NewCourier
from OpenApi.models.order import Order
