# coding: utf-8

# flake8: noqa

"""
    Swagger Delivery

    Отвечает за учет курьеров, деспетчеризацию доставок, доставку

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from OpenApi.api.default_api import DefaultApi

# import ApiClient
from OpenApi.api_response import ApiResponse
from OpenApi.api_client import ApiClient
from OpenApi.configuration import Configuration
from OpenApi.exceptions import OpenApiException
from OpenApi.exceptions import ApiTypeError
from OpenApi.exceptions import ApiValueError
from OpenApi.exceptions import ApiKeyError
from OpenApi.exceptions import ApiAttributeError
from OpenApi.exceptions import ApiException

# import models into sdk package
from OpenApi.models.courier import Courier
from OpenApi.models.error import Error
from OpenApi.models.location import Location
from OpenApi.models.new_courier import NewCourier
from OpenApi.models.order import Order
